config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :pages, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:foursquare]

  has_many :places, dependent: :destroy


  def self.find_for_foursquare_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.access_token = auth.credentials.token
      user.password = Devise.friendly_token[0,20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      image = auth.info.image
      photo_prefix = image.prefix
      photo_suffix = image.suffix
      user.photo = "#{photo_prefix}100x100#{photo_suffix}"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    foursquare_serivce = FoursquareService.new(user: current_user)
    @checkins = foursquare_serivce.get_recent_checkins_formatted
    @wishlist = foursquare_serivce.get_whishlist_formatted
  end

  def create
    place = Place.new(checkin_id: params[:checkin_id], user: current_user)
    if place.save!
      redirect_to root_path
    else
      raise "An error has occured"
    end

  end

  def destroy
    Place.find(params[:id]).destroy
    redirect_to root_path
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def foursquare
    user = User.find_for_foursquare_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Foursquare') if is_navigational_format?
    else
      session['devise.foursquare_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Foursquare Wishlist</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<% unless @wishlist.empty? %>
  <div class="margin-h-sm">
    <h2>Wishlist</h2>
    <ul class="flex-container wrap">
      <% @wishlist.each do |place| %>
        <div class="flex-item">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_url(place[:venue_photo]) %>);">
            <div class="card-description">
              <h2><%= place[:venue_name] %></h2>
            </div>
            <a class="card-link" href="#" ></a>
          </div>
          <div>
            <%= link_to "Del", page_path(place[:place_id]), method: :delete, class: "btn btn-danger margin-top"  %>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="margin-h-sm">
  <h2>Recent</h2>
  <ul class="flex-container wrap">
    <% @checkins.each do |checkin| %>
      <div class="flex-item">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%= image_url(checkin[:venue_photo]) %>);">
          <div class="card-description">
            <h2><%= checkin[:venue_name] %></h2>
          </div>
          <%= image_tag checkin[:user_photo], class: "card-user" %>
          <a class="card-link" href="#" ></a>
        </div>
        <div>
          <%= link_to "Add", pages_path(checkin), method: :post, class: "btn btn-primary margin-top"  %>
        </div>
      </div>
    <% end %>
  </ul>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <p class="navbar-wagon-brand"> Wishlist </p>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <p class="navbar-wagon-item navbar-wagon-link"> <%= current_user.first_name %></p>

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li>
          <% if user_signed_in? %>
            <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
            <% end %>
          <% else %>
            <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</div>